# Generated by cpp11: do not edit by hand

open_unit_ <- function() {
  .Call(`_usbtc08r_open_unit_`)
}

close_unit_ <- function(handle) {
  .Call(`_usbtc08r_close_unit_`, handle)
}

get_last_error_ <- function(handle) {
  .Call(`_usbtc08r_get_last_error_`, handle)
}

error_ <- function(error) {
  .Call(`_usbtc08r_error_`, error)
}
