# Generated by cpp11: do not edit by hand

open_ <- function() {
  .Call(`_usbtc08r_open_`)
}

open_async_ <- function() {
  .Call(`_usbtc08r_open_async_`)
}

open_progress_ <- function() {
  .Call(`_usbtc08r_open_progress_`)
}

close_ <- function(handle) {
  .Call(`_usbtc08r_close_`, handle)
}

get_last_error_ <- function(handle) {
  .Call(`_usbtc08r_get_last_error_`, handle)
}

error_ <- function(error) {
  .Call(`_usbtc08r_error_`, error)
}
