# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Open Unit
#' @export
open_unit <- function() {
    .Call(`_usbtc08r_open_unit`)
}

#' Get Last Error
#' @export
get_last_error <- function(handle) {
    .Call(`_usbtc08r_get_last_error`, handle)
}

